// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    simple_asset_minter
    (
        init => init
        upgrade => upgrade
        mintNftSft => mint_nft_sft_endpoint
        withdraw => withdraw
        issueSemiFungible => issue_semi_fungible
        getIssuedTokenIdentifiers => token_identifiers
    )
}

multiversx_sc_wasm_adapter::async_callback! { simple_asset_minter }
