[package]
name = "assets-remapper-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.assets-remapper]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false
