// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           41
// Async Callback (empty):               1
// Total number of exported functions:  43

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    soul_nft_staking
    (
        init => init
        initConfig => init_config
        setupScores => setup_scores
        stake => stake_souls
        stakeForUser => stake_souls_for_user
        unstake => unstake_souls
        claimRewards => claim_rewards
        distributeRewards => distribute_rewards
        getUserScore => get_user_score
        getAggregatedScore => get_aggregated_score
        getStakeEpoch => get_stake_epoch
        getOuroTokenId => ouro_token_id
        getUsddTokenId => usdd_token_id
        getUsdcTokenId => usdc_token_id
        getWegldTokenId => wegld_token_id
        getKosonTokenId => koson_token_id
        getOriginSoulsNftTokenId => origin_souls_nft_token_id
        getDeathSoulsNftTokenId => death_souls_nft_token_id
        getSummonedSoulsNftTokenId => summoned_souls_nft_token_id
        getTokenIdScore => token_id_score
        getRewardTokenId => reward_token_id
        getAggregatedSoulStakingScores => aggregated_soul_staking_scores
        getUserAggregatedSoulStakingScores => user_aggregated_soul_staking_scores
        getUserUnclaimedRewards => user_unclaimed_rewards
        getStakedSouls => staked_souls
        getSoulStakeEpoch => soul_stake_epoch
        getTotalUnclaimedReward => get_total_unclaimed_reward
        getUnclaimedRewardRate => get_unclaimed_reward_rate
        getCurrentRewardRate => get_current_reward_rate
        getLastClaimedRewardRate => get_last_claimed_reward_rate
        getUnstakeFeePerScoreKoson => get_unstake_fee_per_score_koson
        setPairInfo => set_pair_info
        removePairInfo => remove_pair_info
        getEquivalentVestaDex => get_equivalent_vesta_dex
        getEquivalentXExchange => get_equivalent_xexchange
        getSwapPairAddress => swap_pair_address
        setUmbrellaRegistryAddress => set_oracle_registry_address
        setUmbrellaPriceFeed => set_price_feed
        getUmbrellaPrice => get_oracle_price
        getUmbrellaFeedsAddress => get_feeds_address
        getUmbrellaRegistryAddress => get_umbrella_registry_addr
        getTokenIdentifierFeedMapping => token_identifier_feed_mapping
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
