// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    koson_factory_facade
    (
        init => init
        upgrade => upgrade
        addFactoryAddresses => add_factory_addresses
        removeFactoryAddresses => remove_factory_addresses
        distribute => distribute_factory_rewards
        getFactoryAddressList => factory_address_list
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
