// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    koson_factory_facade
    (
        init => init
        upgrade => upgrade
        initConfig => init_config
        distribute => distribute_factory_rewards
        getChrysopoeicForgeAddress => chrysopoeic_forge_address
        getUniversalForgeAddress => universal_forge_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
