[package]
name = "dex-pair-sc-meta"
version = "0.0.0"
authors = ["DemiourgosHoldings"]
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.dex-pair-sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.48.0"
