// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback:                       1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    assets_remapper
    (
        init => init
        upgrade => upgrade
        mint => mint_nft_sft_endpoint
        migrate => migrate_assets
        getTokenIdentifierMapValue => token_identifier_map
        getTokenIdentifierDetails => token_identifier_details
        issue => issue_token
        mapTokens => map_tokens
    )
}

multiversx_sc_wasm_adapter::async_callback! { assets_remapper }
