[package]
name = "soul-nft-staking-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.soul-nft-staking]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false
