[package]
name = "koson-staking-pool-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.koson-staking-pool]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.3"
default-features = false
