[package]
name = "dex-pair-sc"
version = "0.0.0"
authors = ["DemiourgosHoldings"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.47.3"

[dev-dependencies.multiversx-sc-scenario]
version = "0.47.3"
