// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback:                       1
// Total number of exported functions:  18

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    koson_staking_pool
    (
        init => init
        upgrade => upgrade
        initConfig => init_config
        stake => stake_koson
        startUnstake => unstake_koson
        claimUnstaked => claim_unstaked
        distributeReward => distribute_reward
        issue => issue_token
        getKosonTokenId => koson_token_ids
        getStakedKosonTokenId => staked_koson_token_id
        getUnbondingKosonTokenId => unbonding_koson_token_id
        getKosonSupply => koson_supply
        getStakedKosonSupply => staked_koson_supply
        getUnbondingTimePenalty => unbonding_time_penalty
        getUnclaimedRewardRate => get_unclaimed_reward_rate
        getCurrentRewardRate => get_current_reward_rate
        getLastClaimedRewardRate => get_last_claimed_reward_rate
    )
}

multiversx_sc_wasm_adapter::async_callback! { koson_staking_pool }
